#ifndef _TANGY_HATCH_H_
#define _TANGY_HATCH_H_

#define HT_NONE             (0)
#define HT_SLASHED          (1)
#define HT_BACKSLASHED      (2)
#define HT_HLINED           (3)
#define HT_VLINED           (4)
#define HT_CROSSED          (5)
#define HT_XCROSSED         (6)
#define HT_SOLID            (10)
#define HT_DOTTED           (13)
#define HT_SPARSEDOTTED     (14)
#define HT_VZIGZAG          (15)
#define HT_HZIGZAG          (16)
#define HT_CHECKED          (17)
#define HT_BIGCHECKED       (18)
#define HT_HEX              (20)
#define HT_BRICK            (21)
#define HT_DIAMONDPLATE     (26)
#define HT_NFDIAMONDPLATE   (27)
#define HT_CONCENTRATION    (28)
#define HT_CONCENTRIC       (29)
#define HT_SQRING11         (31)
#define HT_SQRING11WRAP     (32)
#define HT_SQRING9          (33)
#define HT_SQRING9WRAP      (34)
#define HT_SQRING7          (35)
#define HT_SQRING7WRAP      (36)
#define HT_MIKUZUSI         (37)
#define HT_RMIKUZUSI        (38)

#define HT_GRID             (50)

#define HT_UGRID005         (51)
#define HT_UGRID010         (52)
#define HT_UGRID020         (53)
#define HT_UGRID025         (54)
#define HT_UGRID050         (55)
#define HT_UGRID100         (56)
#define HT_UGRID200         (57)

#define HT_CGRID            (59)

#define HT_HSTRIPE          (71)
#define HT_VSTRIPE          (72)
#define HT_HVSTRIPE         (73)
#define HT_PLUSSTRIPE       (74)

#define HT_HISHI            (101)
#define HT_HIGAKI           (102)
#define HT_RAIMON           (103)
#define HT_SEIGAIHA         (104)
#define HT_UROKO            (105)
#define HT_NFUROKO          (106)
#define HT_SHIPPO           (107)
#define HT_NFSHIPPO         (108)
#define HT_MAMESHIBORI      (109)
#define HT_NFMAMESHIBORI    (110)
#define HT_KANOKOSHIBORI    (111)
#define HT_FUNDO            (120)
#define HT_YAGASURI         (121)

#define HT_DUMMY            (999)

extern apair_t hatchtype_ial[];
#endif/*_TANGY_HATCH_H_*/
