int dirnormalize(int xxdir);
int rewindcenter(ob *u, int qdir, int *rx, int *ry);
int applywith(ob *u, char *xpos, int *rx, int *ry);
int find_from(ob *xob, int *risx, int *risy);
int find_to_first(ob *xob, int *riex, int *riey);
int find_to_last(ob *xob, int *riex, int *riey);
int est_seg(ns *xns, ob *u, varray_t *opar, varray_t *segar, int kp, int *zdir, int *rlx, int *rby, int *rrx, int *rty, int *rfx, int *rfy);
int takelastobjpos(ob *lob, int pos, int kp, int *nx, int *ny, int *dir);
int OP_GDUMP(const char *pre, char *mid, ob *u);
int OP_LDUMP(const char *pre, char *mid, ob *u);
int insboxpath(varray_t *xar, int xwd, int xht);
int __solve_dir(ns *xns, ob *u, varray_t *opar, int X, int *ang);
int __solve_fandt(ns *xns, ob *u, varray_t *opar, int X, int *sx, int *sy, int *ex, int *ey);
int EST_curveself(FILE *fp, ob *xu, ns *xns, int *_lx, int *_by, int *_rx, int *_ty);
int EST_curve(FILE *fp, ob *xu, ns *xns, int *_lx, int *_by, int *_rx, int *_ty);
int putobj(ob *u, ns *xns, int *gdir);
int fitobj_LBRT(ob *u, int xxdir, int *x, int *y, int *fx, int *fy, ns *xns);
int fitobj_wdht(ob *u, int xxdir, int *x, int *y, ns *xns);
int eval_dir(ob *u, int *xdir);
int bumpH(int x1, int y1, int x2, int y2, int x, int y, int cdir, int *rgx, int *rgy);
int bumpV(int x1, int y1, int x2, int y2, int x, int y, int cdir, int *rgx, int *rgy);
int bump(int x1, int y1, int x2, int y2, int x, int y, int cdir, int *rgx, int *rgy);
int expand_paren(int bx, int by, int w, int h, int ox, int oy, ob *u);
int expand_sep(int bx, int by, int w, int h, int ox, int oy, ob *u);
int _putchunk_lane(ob *xch, int *rx, int *ry, ns *xns);
int _putchunk(ob *xch, int *x, int *y, ns *xns);
int putchunk(ob *xch, int *x, int *y, ns *xns);
int put(ob *xch, int *x, int *y, ns *xns);
